main: com.velozity.vam.Main
name: VAM
author: Velozity
version: 1.0.0
description: A lightweight auto messenger with custom variables, in-game message adder
api-version: 1.15
load: POSTWORLD

commands:
  vam:
    description: All of the VAM commands

permissions:
  vam.createmessage:
    description: All permissions to add messages & edit the interval timer
    default: op
  vam.edittimer:
    description: Edit the interval timer for each message
    default: op
  vam.reload:
    description: Reload this plugin & update messages
    default: op